spring:
  application:
    name: Task-tracker-telegram-bot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
bot:
  name: toDo_taskTracker_bot
  token: ${BOT_TOKEN}