spring:
  application:
    name: Task-tracker-telegram-bot
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    enabled: false
bot:
  name: toDo_taskTracker_bot
  token: 8562525731:AAETff0eFD46qa_qIN0PkqMAj3bJR2Kojbw