spring:
  application:
    name: Task-tracker-telegram-bot
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${POSTGRES_JDBC_URL:jdbc:postgresql://localhost:5432/telegram_bot}
    username: ${POSTGRES_USERNAME:task_tracker_app}
    password: ${POSTGRES_PASSWORD:abrakadabra}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
bot:
  name: toDo_taskTracker_bot
  token: 8562525731:AAETff0eFD46qa_qIN0PkqMAj3bJR2Kojbw